---

tables:

  events:
    note: Events
    api: v1
    kind: Event
    fields:
      #type: "$.type"
      reason: "$.reason"
      namespace: "$.metadata.namespace"
      #event: "$.metadata.name"
      #first: "$.firstTimestamp"
      last: "$.lastTimestamp"
      count: "$.count"
      involvedobject:
        kind: "$.involvedObject.kind"
        pod: "$.involvedObject.name"
      message: "$.message"

queries:

  events-pods:
    node: Events for Pods
    sort:
      - last
    tables:
      - events
      - pods-addresses
