---

tables:

  tables:
    note: List of all available tables
    aliases:
      - t
      - ta
    hide:
      - references
    sort:
      - file
      - name

  queries:
    note: List of all available queries
    aliases:
      - q
      - qu
    hide:
      - contexts
    sort:
      - file
      - name

  bundles:
    note: List of bundles of queries and tables
    aliases:
      - b
      - bu
    hide:
      - contexts
    sort:
      - file
      - name


bundles:

  list:
    note: List all available metadata
    aliases:
      - l
      - ls
    tables:
      - tables
      - queries
      - bundles
