---

tables:

  tables:
    note: List of all available tables
    hidden:
      - references
    sort:
      - file
      - name

  queries:
    note: List of all available queries
    hidden:
      - context
    sort:
      - file
      - name
