---

tables:

  tables:
    note: List of all available tables
    hide:
      - references
    sort:
      - file
      - name

  queries:
    note: List of all available queries
    hide:
      - contexts
    sort:
      - file
      - name
