---

tables:

  nodes-metrics:
    note: Nodes with Metrics
    api: metrics.k8s.io/v1beta1
    kind: NodeMetrics
    fields:
      node: "$.metadata.name"
      nodeusagecpu:
        - "$.usage.cpu"
        - "lambda x: round(int(x.replace('n','')) / 1000000)"
      nodeusagemem:
        - "$.usage.memory"
        - "lambda x: round(int(x.replace('Ki', '')) / 1024 / 1024, 1)"

  nodes-ips:
    note: Nodes with their IPv4 addresses
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      nodeip: "$.status.addresses[?type='InternalIP'].address"
      podcidr: "$.spec.podCIDR"

  nodes-specs:
    note: Nodes with cpu and memory specs
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      kubelet: "$.status.nodeInfo.kubeletVersion"
      cpu: "$.status.capacity.cpu"
      mem:
        - "$.status.capacity.memory"
        - "lambda x: round(int(x.replace('Ki', '')) / 1024 / 1024, 1)"
      kernel: "$.status.nodeInfo.kernelVersion"
      runtime: "$.status.nodeInfo.containerRuntimeVersion"

  nodes-topology-labels:
    note: Nodes with Topology Labels
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      region: "$.metadata.labels.\"topology.kubernetes.io/region\""
      zone: "$.metadata.labels.\"topology.kubernetes.io/zone\""

  nodes-beta-labels:
    note: Nodes with Beta Labels
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      os: "$.metadata.labels.\"beta.kubernetes.io/os\""
      arch: "$.metadata.labels.\"beta.kubernetes.io/arch\""

  nodes-taints:
    note: Nodes with Taints
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      taints:
        noschedule: "$.spec.taints[?effect='NoSchedule']"
        noexecute: "$.spec.taints[?effect='NoExecute']"

queries:

  nodes:
    note: Nodes with Specs and Topology Data
    tables:
      - nodes-ips
      - nodes-specs
      - nodes-topology-labels
      - nodes-taints

  nodes-beta:
    note: Nodes with Beta Labels and Clusters
    tables:
      - nodes-specs
      - nodes-beta-labels
