---

tables:

  nodes:
    note: Nodes with their IPv4 addresses
    api_version: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      nodeip: "$.status.addresses[?type='InternalIP'].address"

  nodes-specs:
    note: Nodes with cpu and memory specs
    api_version: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      cpu: "$.status.capacity.cpu"
      mem: "$.status.capacity.memory"
      kernel: "$.status.nodeInfo.kernelVersion"

  nodes-labels:
    aliases:
      - nl
    note: Nodes with Labels
    api_version: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      region: "$.metadata.labels.\"topology.kubernetes.io/region\""
      zone: "$.metadata.labels.\"topology.kubernetes.io/zone\""
      legacytier: "$.metadata.labels.\"swsnet.ch/tier\""
      legacyzone: "$.metadata.labels.\"zone\""

  nodes-taints:
    note: Nodes with Taints
    api_version: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      taints:
        noschedule: "$.spec.taints[?effect='NoSchedule']"
        noexecute: "$.spec.taints[?effect='NoExecute']"

queries:

  nodes-topology:
    aliases:
      - nt
    note: Nodes with extra topology data
    tables:
      - nodes
      - nodes-specs
      - nodes-labels
      - nodes-taints
