---

tables:

  nodes-ips:
    note: Nodes with their IPv4 addresses
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      nodeip: "$.status.addresses[?type='InternalIP'].address"
      podcidr: "$.spec.podCIDR"

  nodes-specs:
    note: Nodes with cpu and memory specs
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      kubelet: "$.status.nodeInfo.kubeletVersion"
      cpu: "$.status.capacity.cpu"
      mem:
        - "$.status.capacity.memory"
        - "lambda x: round(int(x.replace('Ki', '')) / 1024 / 1024, 1)"
      kernel: "$.status.nodeInfo.kernelVersion"

  nodes-labels:
    note: Nodes with Labels
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      region: "$.metadata.labels.\"topology.kubernetes.io/region\""
      zone: "$.metadata.labels.\"topology.kubernetes.io/zone\""

  nodes-taints:
    note: Nodes with Taints
    api: v1
    kind: Node
    fields:
      node: "$.metadata.name"
      taints:
        noschedule: "$.spec.taints[?effect='NoSchedule']"
        noexecute: "$.spec.taints[?effect='NoExecute']"

queries:

  nodes:
    note: Nodes with specs and topology data
    tables:
      - nodes-ips
      - nodes-specs
      - nodes-labels
      - nodes-taints
