---

tables:

  pods-addresses:
    note: Pods with adresses and status
    api: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      podip: "$.status.podIPs[*].ip"
      podphase: "$.status.phase"

  pods-images:
    note: Pods and their Containers
    api: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      containers:
        container: "$.spec.containers[*].name"
        image: "$.spec.containers[*].image"

  pods-pvcs:
    note: Pods with PVCs
    api: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      pvc: "$.spec.volumes[*].persistentVolumeClaim.claimName"

  pods-ports:
    note: Pods with Node and containerPort
    api: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      podip: "$.status.podIPs[*].ip"
      port: "$.spec.containers[*].ports[*].containerPort"

  pods-affinity-tolerations:
    note: Pods with affinity and tolerations
    aliases:
      - pat
    api: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      tolerations:
        zone: "$.spec.tolerations[?key='topology.kubernetes.io/zone'].value"
        oldzone: "$.spec.tolerations[?key='zone'].value"
      affinity: "$.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[*]"

queries:

  pods-topology:
    aliases:
      - pt
    note: Pods with various Topology-related attributes
    sort:
      - zone
      - namespace
      - pod
    tables:
      - pods-addresses
      - pods-affinity-tolerations

  pods-nodes-images:
    note: Pods with Nodes and Images
    aliases:
      - pni
    sort:
      - node
      - namespace
      - pod
    tables:
      - nodes-specs
      - pods-images

  pods-nodes-storage:
    note: Pods with Nodes and Storage
    aliases:
      - pns
    sort:
      - zone
      - namespace
      - pod
    tables:
      - pods-addresses
      - nodes-ips
      - nodes-topology-labels
      - pods-pvcs
      - pvcs
      - pvs
