---

tables:

  pods:
    note: Pods with adresses and status
    api_version: v1
    kind: Pod
    fields:
      pod: "$.metadata.name"
      namespace: "$.metadata.namespace"
      node: "$.spec.nodeName"
      podip: "$.status.podIPs[*].ip"
      podphase: "$.status.phase"

  pods-pvcs:
    note: Pods with PVCs
    api_version: v1
    kind: Pod
    fields:
      pod: "$.metadata.name"
      namespace: "$.metadata.namespace"
      node: "$.spec.nodeName"
      pvc: "$.spec.volumes[*].persistentVolumeClaim.claimName"

  pods-ports:
    note: Pods with Node and containerPort
    api_version: v1
    kind: Pod
    fields:
      pod: "$.metadata.name"
      namespace: "$.metadata.namespace"
      node: "$.spec.nodeName"
      podip: "$.status.podIPs[*].ip"
      port: "$.spec.containers[*].ports[*].containerPort"

  pods-tolerations:
    note: Pods with Tolerations
    api_version: v1
    kind: Pod
    fields:
      pod: "$.metadata.name"
      namespace: "$.metadata.namespace"
      tolerations:
        tolerationzone: "$.spec.tolerations[?key='zone'].value"
        tolerationtier: "$.spec.tolerations[?key='swsnet.ch/tier'].value"
      topology:
        topologykey: "$.spec.topologySpreadConstraints[?topologyKey='topology.kubernetes.io/zone'].topologyKey"

queries:

  pods-topology:
    aliases:
      - pt
    note: Pods with various Topology-related attributes
    tables:
      - pods
      - pods-tolerations

  pods-nodes-storage:
    note: Pods with Nodes and Storage
    sort:
      - zone
      - tier
      - namespace
      - pod
    tables:
      - pods
      - nodes
      - nodes-labels
      - pods-pvcs
      - pvcs
      - pvs
