---

tables:

  pods:
    note: Pods with adresses and status
    api_version: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      podip: "$.status.podIPs[*].ip"
      podphase: "$.status.phase"

  pods-pvcs:
    note: Pods with PVCs
    api_version: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      pvc: "$.spec.volumes[*].persistentVolumeClaim.claimName"

  pods-ports:
    note: Pods with Node and containerPort
    api_version: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      node: "$.spec.nodeName"
      podip: "$.status.podIPs[*].ip"
      port: "$.spec.containers[*].ports[*].containerPort"

  pods-affinity-tolerations:
    note: Pods with affinity and tolerations
    api_version: v1
    kind: Pod
    fields:
      namespace: "$.metadata.namespace"
      pod: "$.metadata.name"
      tolerations:
        oldzone: "$.spec.tolerations[?key='zone'].value"
        swstier: "$.spec.tolerations[?key='swsnet.ch/tier'].value"
        region: "$.metadata.labels.\"topology.kubernetes.io/region\""
        zone: "$.metadata.labels.\"topology.kubernetes.io/zone\""
      affinity: "$.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[*]"
      #topology:
      #  top-key: "$.spec.topologySpreadConstraints[?topologyKey='topology.kubernetes.io/zone'].topologyKey"
      #  when-not: "$.spec.topologySpreadConstraints[?topologyKey='topology.kubernetes.io/zone'].whenUnsatisfiable"
      #  maxskew: "$.spec.topologySpreadConstraints[?topologyKey='topology.kubernetes.io/zone'].maxSkew"

queries:

  pods-topology:
    aliases:
      - pt
    note: Pods with various Topology-related attributes
    tables:
      - pods
      - pods-affinity-tolerations

  pods-nodes-storage:
    note: Pods with Nodes and Storage
    sort:
      - zone
      - tier
      - namespace
      - pod
    tables:
      - pods
      - nodes
      - nodes-labels
      - pods-pvcs
      - pvcs
      - pvs
