---

tables:

  pvcs:
    note: PersistentVolumeClaims with Volumes
    aliases:
      - pvc
    api: v1
    kind: PersistentVolumeClaim
    fields:
      pvc: "$.metadata.name"
      namespace: "$.metadata.namespace"
      volume: "$.spec.volumeName"

  pvs:
    note: PersistentVolumes with StorageClass
    aliases:
      - pv
    api: v1
    kind: PersistentVolume
    fields:
      volume: "$.metadata.name"
      pvc: "$.spec.claimRef.name"
      namespace: "$.spec.claimRef.namespace"
      storageclass: "$.spec.storageClassName"

  longhornvolumes:
    note: Longhorn Volumes with size and health
    aliases:
      - lv
    api: longhorn.io/v1beta2
    kind: Volume
    fields:
      volume: "$.metadata.name"
      size: "$.spec.size"
      actualsize: "$.status.actualSize"
      health: "$.status.robustness"
      state: "$.status.state"

  storageclasses:
    note: StorageClasses with parameters
    aliases:
      - sc
    api: v1
    kind: StorageClass
    fields:
      storageclass: "$.metadata.name"
      reclaimpolicy: "$.reclaimPolicy"
      bindingmode: "$.volumeBindingMode"
