---

tables:

  endpointslices:
    note: EndpointSlices with clusterIPs and ports
    api_version: v1
    kind: EndpointSlice
    fields:
      endpoint: "$.metadata.name"
      namespace: "$.metadata.namespace"
      addresses:
        clusterip: "$.endpoints[*].addresses[*]"
        owner: "$.endpoints[*].targetRef.kind"
        node: "$.endpoints[*].targetRef.name"
      ports:
        port: "$.ports[*].port"
        protocol: "$.ports[*].protocol"

queries:

  endpoints-nodes:
    note: Details of clusterIPs on various nodes
    tables:
      - endpointslices
      - nodes
